### ISSUE TITLE
Kernel panic with certain initial ramdisks

### ISSUE THREAD

**Issue by IAmTheNerdNextDoor** [hexagonal-sun/moss-kernel#11]
Created as a follow up from my discussion at pull request #7 and at the request of @hexagonal-sun.

[initrd.zip](https://github.com/user-attachments/files/23698300/initrd.zip)

One thing I noticed is that the initrd is seemingly 134.2MB on my system, which shouldn't happen for an initrd with only 2 directories and 2 files of small sizes.

**Comment by hexagonal-sun** [comment]
Okay, I know what the problem is.  For some reason, /dev on your image isn't associated with a long-file-name (LFN) entry.  Which is fine, my driver supports the old 8.3 filename.  Now old 8.3 filenames are encoded in all caps so, /dev/ results in `/DEV` as the directory entry.  the branch `fat32-case-insensitive` should fix that. 

Bash is now found, however I'm fixing up a few other issues related to libc programs.

**Comment by IAmTheNerdNextDoor** [comment]
Upon bringing your changes into my clone of moss with changes from pull request #7 and clean rebuilding, I now get this.

```
[    0.000000] arch::arm64::boot::memory: Adding memory region from FDT Px40000000 (0x80000000 bytes)
[    0.000000] arch::arm64::boot::memory: Reserving kernel text Px40080000 - Px41117000
[    0.000000] arch::arm64::boot::memory: Reserving FDT Px50000000 (0x100000 bytes)
[    0.000000] arch::arm64::boot::memory: Reserving initrd 0x48000000 - 0x50000000
[    0.000000] libkernel::memory::page_alloc: Buddy allocator initialized. Managing 524288 pages, 463872 free.
[    0.000000] drivers::fs::dev: devfs initialized
[    0.000000] drivers::interrupts::arm_gic_v3: ARM GICv3 found: dist @ <0x8000000, 0x10000>, rdist @ <0x80a0000, 0xf60000> (stride=0x20000)
[    0.000000] drivers::interrupts::arm_gic_v3: GICv3: Redistributor for core 0 (MPIDR=0x80000000) is awake.
[    0.000000] drivers::interrupts::arm_gic_v3: GICv3: CPU interface for core 0 enabled.
[    0.000000] interrupts: Setting device intc@8000000 as the interrupt root
[    0.000000] interrupts: Device timer claimed interrupt: Ppi(14)
[    0.002734] interrupts: Device pl011@9000000 claimed interrupt: Spi(1)
[    0.006142] libkernel::sync::per_cpu: Setup 4 per_cpu objects.
[    0.007640] interrupts: Device CPU Messenger claimed interrupt: Ipi(0)
[    0.098876] drivers::interrupts::arm_gic_v3: GICv3: Redistributor for core 1 (MPIDR=0x80000001) is awake.
[    0.099332] drivers::interrupts::arm_gic_v3: GICv3: CPU interface for core 1 enabled.
[    0.099754] arch::arm64::boot::secondary: CPU 1 online.
[    0.100228] drivers::interrupts::arm_gic_v3: GICv3: Redistributor for core 2 (MPIDR=0x80000002) is awake.
[    0.100662] drivers::interrupts::arm_gic_v3: GICv3: CPU interface for core 2 enabled.
[    0.101018] arch::arm64::boot::secondary: CPU 2 online.
[    0.101502] drivers::interrupts::arm_gic_v3: GICv3: Redistributor for core 3 (MPIDR=0x80000003) is awake.
[    0.101872] drivers::interrupts::arm_gic_v3: GICv3: CPU interface for core 3 enabled.
[    0.102186] arch::arm64::boot::secondary: CPU 3 online.
FATAL: kernel too old
[    0.122848] moss: Kernel Panic: SIGSEGV on process 1 DataAbortLowerEL(AbortIss { ifsc: Ifsc(4), write: false, far: Some(18446744073709550048) }) PC: 525188
```

I have no idea what that "FATAL" message is... nor do I know what the hell happened at all here.

**Comment by hexagonal-sun** [comment]
So you did execute the `bash` code!  But it calls `uname` to see what version the kernel is.  I return `0.1.0` since that's the current version of moss and the program bails with the above message.

You can follow my progress in debugging this on the `libc-program-bringup-fixes` branch (it's based ontop of the fat32 fixes branch for easy testing).

**Comment by IAmTheNerdNextDoor** [comment]
Ah, well that's great! I guess uname or bash needs to be modified in some way to not bail.

I just wanted to say as well that I think this project is really cool and it has big potential! It was shown to me by a member of the kerneldev wiki's discord server that I co-run (they sent a Reddit link and then I saw it on Mastodon).

I've always wanted one of my kernels (especially one of them I'm working on now) to be as cool as this.

Since this is fixed in another branch, do we close or do we wait for the merge into main branch?

**Comment by hardliner66** [comment]
The image size is 134 MB on every system, because thats just how its created. The size is currently hardcoded into the script.

**Comment by IAmTheNerdNextDoor** [comment]
Welp, I don't know how I missed that.

**Comment by hexagonal-sun** [comment]
I think this has largely been addressed?

We're still having issues running `./bin/busybox`, due to missing syscalls, but efforts are on-going to resolve that.

**Comment by IAmTheNerdNextDoor** [comment]
I could close this as resolved if you think that's best?

**Comment by hexagonal-sun** [comment]
I think so, we can now run `bash` in your initrd.  We're now just tackling busybox.

**Comment by IAmTheNerdNextDoor** [comment]
Alright, thanks!
